(in-package #:stumpwm)

(grename "HQ")
(gnew "Transport")
(gnew "Mod-Mat")
(gnew "TV")
(gnew "Radio")
(gnew "Documents")
(gnew "Art")
(gnew "Socials")
(gnew "VHS")
(gnew "Library")
(gnew "Mail")
(gnew "Garden")

;; Gselect:
(define-key *top-map* (kbd "s-1") "gselect 1")
(define-key *top-map* (kbd "s-2") "gselect 2")
(define-key *top-map* (kbd "s-3") "gselect 3")
(define-key *top-map* (kbd "s-4") "gselect 4")
(define-key *top-map* (kbd "s-r") "gselect 5")
(define-key *top-map* (kbd "s-d") "gselect 6")
(define-key *top-map* (kbd "s-a") "gselect 7")
(define-key *top-map* (kbd "s-s") "gselect 8")
(define-key *top-map* (kbd "s-v") "gselect 9")
(define-key *top-map* (kbd "s-x") "gselect 10")
(define-key *top-map* (kbd "s-comma") "gselect 11")
(define-key *top-map* (kbd "s-/") "gselect 12")

(gselect "HQ")
